### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by PerrinAntonin** [ssundaram21/dreamsim#3]
Hello! I'm having a few problems running the training...
I have been able to download the different files and the dataset: nights. I have the impression, that I have placed it in the right place because within the TwoAFCDataset class I can read the csv files, however when I launch the evaluation I have a problem which seems to come from loading the images and the get_preprocess_fn function.
Do you have any idea where the problem might be coming from?

python ./training/train.py --config ./configs/train_ensemble_model_lora.yaml

`
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Using device:  cuda
Global seed set to 1234
./dataset/nights/
<PIL.PngImagePlugin.PngImageFile image mode=RGB size=768x768 at 0x1D02DCF3F10>
<PIL.PngImagePlugin.PngImageFile image mode=RGB size=768x768 at 0x1D02E293650>
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Using cache found in ./models\facebookresearch_dino_main
C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\peft\tuners\lora.py:143: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.
  warnings.warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
Traceback (most recent call last):
  File "C:\Users\A20483\Documents\dreamsim\training\train.py", line 283, in <module>
    run(args, device)
  File "C:\Users\A20483\Documents\dreamsim\training\train.py", line 272, in run
    trainer.validate(model, val_loader)
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 630, in validate
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 673, in _validate_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 975, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1011, in _run_stage
    return self._evaluation_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 98, in run
    self.setup_data()
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 168, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 385, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
    ^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\A20483\AppData\Local\miniforge3\envs\banger\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_preprocess_fn.<locals>.<lambda>'`

**Comment by ssundaram21** [comment]
Hi - thanks for bringing this up. It looks like the dataset is in the right directory. Could you confirm which versions of Pytorch and Pytorch Lightning you are using so we can try to reproduce the error?

**Comment by PerrinAntonin** [comment]
I'm using the version: 2.0.3 for pytorch-lightning
and the version 2.0.1+cu118 for torch

**Comment by Netanel-Tamir** [comment]
Can you send us the entire pip list of your environment?

**Comment by PerrinAntonin** [comment]
Yes for sure !
Package                       Version
----------------------------- -----------
absl-py                       1.4.0
accelerate                    0.20.3
aiohttp                       3.8.4
aiosignal                     1.3.1
asttokens                     2.2.1
astunparse                    1.6.3
async-timeout                 4.0.2
attrs                         23.1.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bitsandbytes                  0.39.0
bitsandbytes-windows          0.37.5
cachetools                    5.3.1
certifi                       2023.5.7
charset-normalizer            3.1.0
click                         8.1.3
clip                          0.2.0
colorama                      0.4.6
comm                          0.1.3
ConfigArgParse                1.5.3
contourpy                     1.0.7
cycler                        0.11.0
debugpy                       1.6.7
decorator                     5.1.1
dreamsim                      0.1.1
easyfsl                       1.4.0
executing                     1.2.0
filelock                      3.12.2
flatbuffers                   23.5.26
fonttools                     4.40.0
frozenlist                    1.3.3
fsspec                        2023.6.0
ftfy                          6.1.1
gast                          0.4.0
google-auth                   2.19.1
google-auth-oauthlib          1.0.0
google-pasta                  0.2.0
grpcio                        1.54.2
h5py                          3.8.0
huggingface-hub               0.15.1
idna                          3.4
importlib-metadata            6.6.0
ipykernel                     6.23.1
ipython                       8.14.0
ipywidgets                    8.0.6
jax                           0.4.12
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.2.0
jupyter_client                8.2.0
jupyter_core                  5.3.0
jupyterlab-widgets            3.0.7
keras                         2.12.0
kiwisolver                    1.4.4
libclang                      16.0.0
lightning-utilities           0.8.0
llvmlite                      0.40.1rc1
Markdown                      3.4.3
MarkupSafe                    2.1.3
matplotlib                    3.7.1
matplotlib-inline             0.1.6
ml-dtypes                     0.2.0
mpmath                        1.3.0
multidict                     6.0.4
nest-asyncio                  1.5.6
networkx                      3.1
nltk                          3.8.1
numba                         0.57.0
numpy                         1.23.5
oauthlib                      3.2.2
open-clip-torch               2.20.0
opencv-python                 4.7.0.72
opt-einsum                    3.3.0
packaging                     23.1
pandas                        2.0.2
parso                         0.8.3
peft                          0.1.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.1.2
platformdirs                  3.5.3
prompt-toolkit                3.0.38
protobuf                      3.20.3
psutil                        5.9.5
pure-eval                     0.2.2
pyasn1                        0.5.0
pyasn1-modules                0.3.0
Pygments                      2.15.1
pyod                          1.0.9
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytorch-lightning             2.0.3
pytz                          2023.3
pywin32                       304
PyYAML                        6.0
pyzmq                         25.1.0
regex                         2023.6.3
requests                      2.31.0
requests-oauthlib             1.3.1
rsa                           4.9
safetensors                   0.3.1
scikit-learn                  1.2.2
scipy                         1.10.1
segment-anything              1.0
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    67.7.2
six                           1.16.0
stack-data                    0.6.2
sympy                         1.12
tensorboard                   2.12.3
tensorboard-data-server       0.7.0
tensorflow                    2.12.0
tensorflow-estimator          2.12.0
tensorflow-intel              2.12.0
tensorflow-io-gcs-filesystem  0.31.0
termcolor                     2.3.0
threadpoolctl                 3.1.0
timm                          0.9.2
tokenizers                    0.13.3
torch                         2.0.1+cu118
torchmetrics                  0.11.4
torchvision                   0.15.2
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.9.0
transformers                  4.30.1
typing_extensions             4.6.3
tzdata                        2023.3
urllib3                       1.26.16
wcwidth                       0.2.6
Werkzeug                      2.3.6
wheel                         0.40.0
widgetsnbextension            4.0.7
win-inet-pton                 1.1.0
wrapt                         1.14.1
yarl                          1.9.2
zipp                          3.15.0

**Comment by Netanel-Tamir** [comment]
Have you installed the packages from the requirements.txt file? 
I'm asking because I see that you're missing some of the packages.
This is required for training.

**Comment by PerrinAntonin** [comment]
Maybe the probIem come from this! i will try tomorrow.
But it seem weird because the only packages which are missing are: dists-pytorch lpips (which is not used) and pyYaml (that weird because the serialization seems to work)

**Comment by PerrinAntonin** [comment]
I've found the problem, it comes from multiprocessing, when I set num_workers=0 the error disappears

**Comment by Netanel-Tamir** [comment]
Glad you found a solution.
Does replacing the lambda function with an actual function in line 39 of the get_preprocess_fn solve the issue as well while enabling multiprocessing?

**Comment by PerrinAntonin** [comment]
I didn't try but from what I saw in internet this could help
